#!/bin/bash

ln -fs "$PWD/inputrc" "$HOME/.inputrc"
ln -fs "$PWD/rc.bash" "$HOME/.bashrc"
ln -fs "$PWD/profile.bash" "$HOME/.bash_profile"
ln -fs "$PWD/aliases.bash" "$HOME/.bash_aliases"
ln -fs "$PWD/colors.bash" "$HOME/.bash_colors"
ln -fs "$PWD/functions.bash" "$HOME/.bash_functions"
ln -fs "$PWD/dircolors" "$HOME/.dircolors"
